# Generated by Django 4.2 on 2023-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('city1', models.TextField(blank=True, null=True)),
                ('city2', models.TextField(blank=True, null=True)),
                ('city2_english', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
