# Generated by Django 4.2 on 2023-06-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
