# Generated by Django 4.2 on 2023-06-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_message_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
