# Generated by Django 4.2 on 2023-04-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
