# Generated by Django 4.2 on 2023-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
